In [4]:
import pandas as pd

df = pd.read_csv("Downloads/Ecommerce_Sales_Data_2024_2025.csv")
print(df.head())

   Order ID  Order Date Customer Name Region       City   Category  \
0     10001  19-10-2024  Kashvi Varty  South  Bangalore      Books
1     10002  30-08-2025   Advik Desai  North      Delhi  Groceries
2     10003  04-11-2023    Rhea Kalla   East      Patna    Kitchen
3     10004  23-05-2025     Anika Sen   East    Kolkata  Groceries
4     10005  19-01-2025   Akarsh Kaul   West       Pune   Clothing

  Sub-Category       Product Name  Quantity  Unit Price  Discount     Sales  \
0  Non-Fiction  Non-Fiction Ipsum         2       36294         5   68958.6
1         Rice          Rice Nemo         1       42165        20   33732.0
2       Juicer        Juicer Odio         4       64876        20  207603.2
3          Oil      Oil Doloribus         5       37320        15  158610.0
4    Kids Wear      Kids Wear Quo         1       50037        10   45033.3

     Profit Payment Mode
0  10525.09   Debit Card
1   6299.66   Debit Card
2  19850.27  Credit Card
3  36311.02          UPI
4   9050.04   Debit Card

In [6]:
print(df.shape)

(5000, 14)

In [7]:
print(df.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5000 entries, 0 to 4999
Data columns (total 14 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Order ID       5000 non-null   int64
 1   Order Date     5000 non-null   object
 2   Customer Name  5000 non-null   object
 3   Region         5000 non-null   object
 4   City           5000 non-null   object
 5   Category       5000 non-null   object
 6   Sub-Category   5000 non-null   object
 7   Product Name   5000 non-null   object
 8   Quantity       5000 non-null   int64
 9   Unit Price     5000 non-null   int64
 10  Discount       5000 non-null   int64
 11  Sales          5000 non-null   float64
 12  Profit         5000 non-null   float64
 13  Payment Mode   5000 non-null   object
dtypes: float64(2), int64(4), object(8)
memory usage: 547.0+ KB
None

In [8]:
print(df.describe())

           Order ID     Quantity    Unit Price     Discount          Sales  \
count   5000.000000  5000.000000   5000.000000  5000.000000    5000.000000
mean   12500.500000     2.992600  39760.904600    10.051000  106733.204870
std     1443.520003     1.413133  22831.783946     7.084662   85108.208202
min    10001.000000     1.000000    222.000000     0.000000     264.100000
25%    11250.750000     2.000000  20312.250000     5.000000   39766.537500
50%    12500.500000     3.000000  39459.500000    10.000000   83080.325000
75%    13750.250000     4.000000  59721.750000    15.000000  156968.587500
max    15000.000000     5.000000  79998.000000    20.000000  398485.000000

             Profit
count   5000.000000
mean   15941.746982
std    14897.684916
min       19.120000
25%     4892.295000
50%    11108.525000
75%    22467.987500
max    89688.440000

In [9]:
df.isnull().sum()

Order ID         0
Order Date       0
Customer Name    0
Region           0
City             0
Category         0
Sub-Category     0
Product Name     0
Quantity         0
Unit Price       0
Discount         0
Sales            0
Profit           0
Payment Mode     0
dtype: int64

In [4]:
df.duplicated().sum()

np.int64(0)

In [14]:
# Date conversion

df["Order date"] = pd.to_datetime(
    df["Order Date"],
    format = "%d-%m-%Y"
)

print(df['Order Date'].dtype)

object

In [15]:
print(df["Order Date"].head(10))

0    19-10-2024
1    30-08-2025
2    04-11-2023
3    23-05-2025
4    19-01-2025
5    06-04-2025
6    13-10-2023
7    17-08-2025
8    07-03-2025
9    02-12-2024
Name: Order Date, dtype: object

In [16]:
import pandas as pd

df["Order Date"] = pd.to_datetime(
    df["Order Date"],
    format="%d-%m-%Y"
)

print(df["Order Date"].head())

print(df["Order Date"].dtype)

0   2024-10-19
1   2025-08-30
2   2023-11-04
3   2025-05-23
4   2025-01-19
Name: Order Date, dtype: datetime64[ns]
datetime64[ns]

In [20]:
# Date features:

df["Year"] = df["Order Date"].dt.year
df["Month"] = df["Order Date"].dt.month
df["Month_Name"] = df["Order Date"].dt.month_name()
df["Quarter"] = df["Order Date"].dt.quarter


df[["Order Date","Year","Month","Month_Name","Quarter"]].head()

  Order Date  Year  Month Month_Name  Quarter
0 2024-10-19  2024     10    October        4
1 2025-08-30  2025      8     August        3
2 2023-11-04  2023     11   November        4
3 2025-05-23  2025      5        May        2
4 2025-01-19  2025      1    January        1

In [3]:
# check the profit margin

df["Profit Margin%"] = (
    df["Profit"]/df["Sales"]
)*100

df[["Sales","Profit","Profit Margin%"]].head(5)

      Sales    Profit  Profit Margin%
0   68958.6  10525.09       15.262911
1   33732.0   6299.66       18.675620
2  207603.2  19850.27        9.561640
3  158610.0  36311.02       22.893273
4   45033.3   9050.04       20.096329

In [4]:
# Important KPIs

# Total sales
print("Total Sales =", round(df["Sales"].sum(),2))

Total Sales = 533666024.35

In [5]:
# Total Profit
print("Total Profit =", round(df["Profit"].sum(),2))

Total Profit = 79708734.91

In [8]:
# Total orders
print("Total Orders =", df["Order ID"].nunique())

Total Orders = 5000

In [9]:
# Average order value
print("Average Order value =", round(df["Sales"].mean(),2))

Average Order value = 106733.2

In [10]:
# Category wise sales Analysis

Category_sales = (
    df.groupby("Category")["Sales"]
    .sum()
    .sort_values(ascending = False)
)

print(Category_sales)

Category
Home Decor     57233222.35
Furniture      56647187.90
Clothing       55053908.30
Books          54932643.00
Kitchen        54227902.30
Electronics    52587883.95
Toys           52227366.45
Sports         52069397.25
Beauty         50803409.70
Groceries      47883103.15
Name: Sales, dtype: float64

In [12]:
# Region wise sales Analysis

region_sales = (
    df.groupby("Region")["Sales"]
    .sum()
    .sort_values(ascending = False)
)
print(region_sales)

Region
North    1.435782e+08
East     1.358116e+08
West     1.310460e+08
South    1.232302e+08
Name: Sales, dtype: float64

In [13]:
# Payment Mode Analysis

payment_sales = (
    df.groupby("Payment Mode")["Sales"]
    .sum()
    .sort_values(ascending=False)
)

print(payment_sales)

Payment Mode
Net Banking    1.114655e+08
COD            1.088814e+08
Credit Card    1.060271e+08
Debit Card     1.053464e+08
UPI            1.019456e+08
Name: Sales, dtype: float64